# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url_index',
            old_name='word',
            new_name='text',
        ),
    ]
